### ISSUE TITLE
Bad Words System not working in Linux os

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/javascript#1]
Hello,

How can i make this work in a linux/ubuntu os?

javascript/Discord Bot Maker (DBM)/RAW Data/Bad Words System/

[https://github.com/DanTheComputerMan/javascript/tree/master/Discord%20Bot%20Maker%20(DBM)/RAW%20Data/Bad%20Words%20System](https://github.com/DanTheComputerMan/javascript/tree/master/Discord%20Bot%20Maker%20(DBM)/RAW%20Data/Bad%20Words%20System)

**Comment by master3395** [comment]
As you can see on the image, using the command ";BadWordsSetup config wordtype check"
Only responds with the default message.
And no, i haven't edited anything in that filter system.
![image](https://user-images.githubusercontent.com/4199669/65358421-d9449180-dbf9-11e9-821e-0995c707c69a.png)

**Comment by DanTheComputerMan** [comment]
This was made on Windows, for Windows. If you can get it working on another OS, that's awesome.
