### ISSUE TITLE
Bad Words System capital letter bug

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/javascript#11]
Hello, for some reason after the bot is restarted all words added with a capital letter, is not recognized as a bad word.
Only small letters are. (Yes i am hosting this on windows computer using cmd at this time).

![image](https://user-images.githubusercontent.com/4199669/92631522-c414b700-f2d1-11ea-8238-a7defc49041c.png)

**Comment by DanTheComputerMan** [comment]
The system is getting a rework. What this means is that you will have to replace the bad word system with the new one, unfortunately losing any custom bad words in the list and custom settings. Don't fret though! There are many exciting features planned in the upcoming version.
