### ISSUE TITLE
Suggestion: Show bad word

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/javascript#3]
When you're getting a dm, it shows the whole sentence as bad.
I think it should show the whole sentence, but highlight the word, that is banned.

**Comment by DanTheComputerMan** [comment]
From what I can tell, this is already a thing. Could you provide more information (e.g. a Screenshot)?

**Comment by master3395** [comment]
I noticed that it didn't dm you at all, it only sent it to the log channel (i mistook this bad word system and an old system i had)

But i do think that there should be a way to auto dm the user that gets the message deleted, the word, that get's deleted, just like it is showing below, in case someone just says "why did my message get deleted"

![image](https://user-images.githubusercontent.com/4199669/74186469-fcc0b500-4c4a-11ea-9687-8795b09467cb.png)

**Comment by DanTheComputerMan** [comment]
The system is getting a rework. What this means is that you will have to replace the bad word system with the new one, unfortunately losing any custom bad words in the list and custom settings. Don't fret though! There are many exciting features planned in the upcoming version.
