### ISSUE TITLE
Bad Words System capital VS non capital

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/javascript#4]
Hello, is there any way of doing check for both capital and non-capital.
As of right now, the way i got it set up.
It only searches for that exact word, if it's capital or not.
Not as a wildcard.
So if i block
Test
It doesn't block
test.

**Comment by DanTheComputerMan** [comment]
This is a planned feature, though no time table is expected.

**Comment by DanTheComputerMan** [comment]
The system is getting a rework. What this means is that you will have to replace the bad word system with the new one, unfortunately losing any custom bad words in the list and custom settings. Don't fret though! There are many exciting features planned in the upcoming version.
