### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/javascript#7]
Hi, I've got a new issue.
This system does not work with the new Beta version.
I had to revert back to the old, in order to make it work again.

Not sure what has happened, but even generalwrex has to re-write his serverprefix js code.
Could it be some code change in the new beta version not being compatible?

Also, fs is phased out, perhaps replace with fs-extra?
https://www.npmjs.com/package/fs-extra

**Comment by DanTheComputerMan** [comment]
I can take a look at differences.
GitHub issues don't state what a comment is in reference to. Can you let me know what of mine uses the fs module?

**Comment by master3395** [comment]
Sorry, my mistake.
I took it for the command prefix for each server, that Wrex has made.
