### ISSUE TITLE
Bad Words System not banning

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/javascript#8]
Hello.
The banning from the Bad Words System, does not work anymore.
It does send a message to the user that has reached 3 warnings, but it does not ban the user.
And all warning points are reset back to 0

![unknown](https://user-images.githubusercontent.com/4199669/77794431-29e6ec80-706c-11ea-9524-9826fdeea626.png)

![image](https://user-images.githubusercontent.com/4199669/77794494-4b47d880-706c-11ea-9839-7a46e397a44e.png)

**Comment by master3395** [comment]
In BadWordsFilter, it says it can kick and ban a user.
But it does not do so.

**Comment by DanTheComputerMan** [comment]
The system is getting a rework. What this means is that you will have to replace the bad word system with the new one, unfortunately losing any custom bad words in the list and custom settings. Don't fret though! There are many exciting features planned in the upcoming version.
